#!/usr/bin/env bash
# ==============================================================================
# collect_evidence.sh — snapshot the running homelab into a redacted report
#
# Run this ON the instance:
#     bash /opt/homelab/scripts/collect_evidence.sh > /tmp/evidence.md
#
# Then copy the result to your laptop and commit it under docs/evidence/.
#
# WHY THIS EXISTS
# The README makes claims about a system nobody else can log into. This script
# produces the closest thing to an audit trail that a private instance can
# offer: a timestamped, machine-generated snapshot of what was actually running,
# gathered by one command rather than assembled by hand.
#
# It is evidence, not proof. Anyone can edit a markdown file. What it is good
# for is being specific and internally consistent — the row count in the health
# log has to agree with the uptime, the container has to have been started
# before the checks that probed it — and being reproducible on demand.
#
# WHAT IT REDACTS
# Public IPv4 addresses and 12-digit AWS account IDs are masked before output.
# Private RFC1918 addresses are kept, because they carry design information and
# reveal nothing: 10.0.1.58 tells a reader the subnet layout matches the
# Terraform and gets them no closer to the host. Instance IDs and availability
# zones are kept for the same reason.
#
# Deliberately NOT collected: the public IP, the SSH CIDR allow-list, anything
# from ~/.aws, and any environment variable. Publishing the address of a live
# host to prove it is live is a bad trade.
# ==============================================================================
set -uo pipefail

LOG_FILE="/opt/homelab/logs/uptime.csv"
ENDPOINT="http://127.0.0.1:5000/health"

# --- IMDSv2 ---
# Ubuntu 22.04 on current AWS defaults requires a token; the older unauthenticated
# GET returns 401. Failures here are non-fatal: the report is still useful without
# instance metadata, and this script should never be the thing that breaks.
imds() {
    local token path
    path="$1"
    token=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" \
        -H "X-aws-ec2-metadata-token-ttl-seconds: 60" --max-time 2 2>/dev/null)
    if [[ -z "$token" ]]; then
        echo "unavailable"
        return 0
    fi
    curl -s -H "X-aws-ec2-metadata-token: ${token}" --max-time 2 \
        "http://169.254.169.254/latest/meta-data/${path}" 2>/dev/null || echo "unavailable"
}

emit() {
    echo "# Homelab evidence snapshot"
    echo
    echo "Generated by \`scripts/collect_evidence.sh\` at **$(date -u '+%Y-%m-%d %H:%M:%S') UTC**."
    echo "Public IPs and AWS account IDs are masked; see the header of that script"
    echo "for what is collected and what is deliberately left out."
    echo

    echo "## Instance"
    echo
    echo '```'
    echo "instance-id       : $(imds instance-id)"
    echo "instance-type     : $(imds instance-type)"
    echo "availability-zone : $(imds placement/availability-zone)"
    echo "ami-id            : $(imds ami-id)"
    echo "private-ipv4      : $(imds local-ipv4)"
    echo "hostname          : $(hostname)"
    echo "kernel            : $(uname -r)"
    echo "os                : $(. /etc/os-release && echo "${PRETTY_NAME}")"
    echo "uptime            : $(uptime -p)"
    echo "booted            : $(uptime -s) UTC"
    echo '```'
    echo

    echo "## Health check history"
    echo
    if [[ -f "$LOG_FILE" ]]; then
        echo '```'
        awk -F, '
            NR == 2 { first = $1 }
            NR > 1  { n++; total += $3; if ($3 > max) max = $3; if ($4 != "true") fail++; last = $1 }
            END {
                if (n == 0) { print "no rows recorded yet"; exit }
                printf "rows            : %d\n", n
                printf "first check     : %s\n", first
                printf "last check      : %s\n", last
                printf "failed checks   : %d\n", fail + 0
                printf "success rate    : %.2f%%\n", (n - fail) * 100 / n
                printf "mean response   : %.1f ms\n", total / n
                printf "max response    : %d ms\n", max
            }
        ' "$LOG_FILE"
        echo '```'
        echo
        echo "The check runs from cron every five minutes. Multiply the row count by"
        echo "five and compare it against the uptime above: if a run had been missed,"
        echo "the two would disagree."
        echo
        echo "Last ten rows:"
        echo
        echo '```'
        head -1 "$LOG_FILE"
        tail -10 "$LOG_FILE"
        echo '```'
    else
        echo "\`${LOG_FILE}\` does not exist — the cron health check has never run."
    fi
    echo

    echo "## Application"
    echo
    echo '```'
    echo "\$ curl -s -o /dev/null -w '%{http_code} in %{time_total}s\\n' ${ENDPOINT}"
    curl -s -o /dev/null -w '%{http_code} in %{time_total}s\n' --max-time 5 "$ENDPOINT" 2>/dev/null \
        || echo "no response"
    echo
    echo "\$ docker ps"
    docker ps 2>/dev/null || sudo docker ps 2>/dev/null || echo "docker unavailable to this user"
    echo '```'
    echo
    echo "The \`(healthy)\` marker is the Compose healthcheck. It probes with"
    echo "\`python -c\` and urllib rather than curl, because the image is built from"
    echo "\`python:3.11-slim\`, which ships no curl — an earlier probe failed on every"
    echo "run while the endpoint returned 200 throughout."
    echo

    echo "## Services"
    echo
    echo '```'
    for unit in homelab.service docker.service amazon-cloudwatch-agent.service cron.service; do
        printf '%-38s %s / %s\n' "$unit" \
            "$(systemctl is-enabled "$unit" 2>/dev/null || echo unknown)" \
            "$(systemctl is-active  "$unit" 2>/dev/null || echo unknown)"
    done
    echo
    echo "cloud-init: $(cloud-init status 2>/dev/null | head -1 || echo unavailable)"
    echo
    echo "cron entry:"
    cat /etc/cron.d/homelab-health 2>/dev/null || echo "  not installed"
    echo '```'
    echo

    echo "## Resources"
    echo
    echo '```'
    df -h / | sed -n '1p;2p'
    echo
    free -m | sed -n '1p;2p'
    echo '```'
    echo

    echo "## What this does and does not show"
    echo
    echo "**Shows:** that the instance exists, what it is running, that the systemd"
    echo "units are enabled as well as active — so it survives a reboot, not just"
    echo "this moment — and that the health check has been recording continuously"
    echo "since the timestamp above."
    echo
    echo "**Does not show:** anything a reader can independently verify. This is a"
    echo "text file generated on a host only I can reach. Treat it as a specific,"
    echo "checkable claim rather than as proof: the numbers here have to agree with"
    echo "each other and with the Terraform in this repository, and I can regenerate"
    echo "it live on request."
}

# --- Redaction -----------------------------------------------------------------
# Two passes. A single blanket IPv4 rule would eat the private addresses too, and
# a marker made of punctuation does not protect them — sed's word boundaries still
# match the digits inside it. So private and loopback addresses have their dots
# swapped for a token first, which makes them unmatchable by the dotted-quad rule,
# and the token is swapped back at the end.
emit | sed -E \
    -e 's/\b(10|127)\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\b/\1_DOT_\2_DOT_\3_DOT_\4/g' \
    -e 's/\b(192)\.(168)\.([0-9]{1,3})\.([0-9]{1,3})\b/\1_DOT_\2_DOT_\3_DOT_\4/g' \
    -e 's/\b(172)\.(1[6-9]|2[0-9]|3[01])\.([0-9]{1,3})\.([0-9]{1,3})\b/\1_DOT_\2_DOT_\3_DOT_\4/g' \
    -e 's/\b[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\b/<redacted-public-ip>/g' \
    -e 's/\b[0-9]{12}\b/<redacted-account-id>/g' \
    -e 's/_DOT_/./g'
